sclang: don't use mac-specific bullet char for mark in parse error reports
instead, underline the text that caused the error, example:

ERROR: syntax error, unexpected KEYBINOP
  in file 'selected text'
  line 2 char 16:

  [1,2,5 + foobar:,4];
           ^^^^^^^