class library: ndefgui handle buffer instance as argument
avoids ERROR: Message 'rate' not understood when calling .gui on a Ndef with a Buffer instance argument.
Buffer does not implement .rate so need to check for that.